CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stripePaymentIntentId` varchar(100),
	`stripeCheckoutSessionId` varchar(100),
	`customerEmail` varchar(320) NOT NULL,
	`customerName` varchar(200),
	`userId` int,
	`productId` int NOT NULL,
	`productName` varchar(200) NOT NULL,
	`productCategory` varchar(50) NOT NULL,
	`amountInCents` int NOT NULL,
	`status` enum('pending','paid','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`deliveryType` varchar(50),
	`shippingAddress` text,
	`trackingCode` varchar(100),
	`scheduledAt` timestamp,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_stripePaymentIntentId_unique` UNIQUE(`stripePaymentIntentId`),
	CONSTRAINT `orders_stripeCheckoutSessionId_unique` UNIQUE(`stripeCheckoutSessionId`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(100) NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`shortDescription` varchar(300),
	`category` enum('ensaio','obra_arte','ceramica','print','mentoria') NOT NULL,
	`priceInCents` int NOT NULL,
	`compareAtPriceInCents` int,
	`imageUrl` text,
	`images` text,
	`stripePriceId` varchar(100),
	`stripeProductId` varchar(100),
	`deliveryType` enum('agendamento','envio_fisico','download','acesso_online') NOT NULL DEFAULT 'agendamento',
	`stock` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`order` int NOT NULL DEFAULT 0,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_slug_unique` UNIQUE(`slug`)
);
